services:
  - type: web
    name: vip-tracking-system
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: SYSTEM_PASSWORD
        value: MonkeyTilt2024!
