services:
  - type: web
    name: vip-tracking-system
    env: static
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
